/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ppl_delite_cuda_DeliteCudaDriver */

#ifndef _Included_ppl_delite_cuda_DeliteCudaDriver
#define _Included_ppl_delite_cuda_DeliteCudaDriver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaInit
  (JNIEnv *, jclass);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaDevSet
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaDevSet
  (JNIEnv *, jobject, jint);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaDestroyContext
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaDestroyContext
  (JNIEnv *, jobject, jint);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaGetDevNum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaGetDevNum
  (JNIEnv *, jobject);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaCreateStream
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaCreateStream
  (JNIEnv *, jobject);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaDestroyStream
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaDestroyStream
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaStreamSync
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaStreamSync
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaGetFunction
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaGetFunction
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemAlloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemAlloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemFree
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemFree
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemAllocHost
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemAllocHost
  (JNIEnv *, jobject, jint);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemHostGetDevicePointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemHostGetDevicePointer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemCpyHtoDAsync
 * Signature: (J[DIIJJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemCpyHtoDAsync
  (JNIEnv *, jobject, jlong, jdoubleArray, jint, jint, jlong, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemCpyDtoHAsync
 * Signature: ([DJIIJJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemCpyDtoHAsync
  (JNIEnv *, jobject, jdoubleArray, jlong, jint, jint, jlong, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemCpyHtoDAsyncFloat
 * Signature: (J[FIIJJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemCpyHtoDAsyncFloat
  (JNIEnv *, jobject, jlong, jfloatArray, jint, jint, jlong, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemCpyDtoHAsyncFloat
 * Signature: ([FJIIJJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemCpyDtoHAsyncFloat
  (JNIEnv *, jobject, jfloatArray, jlong, jint, jint, jlong, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemCpyHtoDAsyncInt
 * Signature: (J[IIIJJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemCpyHtoDAsyncInt
  (JNIEnv *, jobject, jlong, jintArray, jint, jint, jlong, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemCpyDtoHAsyncInt
 * Signature: ([IJIIJJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemCpyDtoHAsyncInt
  (JNIEnv *, jobject, jintArray, jlong, jint, jint, jlong, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaMemCpyDtoD
 * Signature: (JJI)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaMemCpyDtoD
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    initIDs
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_initIDs
  (JNIEnv *, jobject);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaAsyncLaunch1D
 * Signature: (JLjava/lang/Object;IJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaAsyncLaunch1D
  (JNIEnv *, jobject, jlong, jobject, jint, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaAsyncLaunch2D
 * Signature: (JLjava/lang/Object;IIJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaAsyncLaunch2D
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaAsyncLaunch1DSpec
 * Signature: (JLjava/lang/Object;IIJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaAsyncLaunch1DSpec
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaAsyncLaunch2DSpec
 * Signature: (JLjava/lang/Object;IIIIJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaAsyncLaunch2DSpec
  (JNIEnv *, jobject, jlong, jobject, jint, jint, jint, jint, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaAsync3D3I
 * Signature: (JJJJIIIJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaAsync3D3I
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint, jint, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaAsync3D3IReg
 * Signature: (JJJJIIIJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaAsync3D3IReg
  (JNIEnv *, jobject, jlong, jlong, jlong, jlong, jint, jint, jint, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    cudaSched
 * Signature: (JJIJ)V
 */
JNIEXPORT void JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_cudaSched
  (JNIEnv *, jobject, jlong, jlong, jint, jlong);

/*
 * Class:     ppl_delite_cuda_DeliteCudaDriver
 * Method:    readDevTimeStamp
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ppl_delite_cuda_DeliteCudaDriver_readDevTimeStamp
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
