function [nx,ny] = DrawTree_subfunc_get_subplot_grid(num_plots)
subplot_grid = [1, 1; ...
                1, 2; ...
                2, 2; ...
                2, 2; ...
                2, 3; ...
                2, 3; ...
                2, 4; ...
                3, 3; ...
                3, 3; ...
                3, 4; ...
                3, 4; ...
                3, 4; ...
                3, 5; ...
                3, 5; ...
                3, 5; ...
                4, 4; ...
                4, 5; ...
                4, 5; ...
                4, 5; ...
                4, 5; ...
                4, 6; ...
                4, 6; ...
                4, 6; ...
                4, 6; ...
                5, 5; ...
                5, 6; ...
                5, 6; ...
                5, 6; ...
                5, 6; ...
                5, 6; ...
                5, 7; ...
                5, 7; ...
                5, 7; ...
                5, 7; ...
                5, 7; ...
                5, 8; ...
                5, 8; ...
                5, 8; ...
                5, 8; ...
                5, 8; ...
                6, 8; ...
                6, 8; ...
                6, 8; ...
                6, 8; ...
                6, 8; ...
                6, 8; ...
                6, 8; ...
                6, 8; ...
                7, 8; ...
                7, 8; ...
                7, 8; ...
                7, 8; ...
                7, 8; ...
                7, 8; ...
                7, 8; ...
                7, 8; ...
                8, 8; ...
                8, 8; ...
                8, 8; ...
                8, 8; ...
                8, 8; ...
                8, 8; ...
                8, 8; ...
                8, 8; ...
                ];                
if num_plots>size(subplot_grid,1)
    error('Error: ask Peng how to fix this, or, look at the above variable in this function and figure it out yourself :)');
    return
end
nx = subplot_grid(num_plots,1);
ny = subplot_grid(num_plots,2);
return